### ISSUE TITLE
Opensuse 42.1 libjpeg8-devel issue

### ISSUE THREAD

**Issue by Mirppc** [HouzuoGuo/headmore#4]
This is just a minor issue but when i go to try and install libjpeg8-devel i get an error saying that it conflicts with libjpeg62-devel.

Which should i keep (?_?)

Will this work with Libjpeg62?

*a few seconds later*

Found another one.. the libpng16-compat-devel conflicts with libpng12-compat-devel.

http://paste.opensuse.org/61118876

(@_@)

**Comment by HouzuoGuo** [comment]
Here's the list of relevant packages that I have installed on this Leap 42.2 system:

<pre>
libjpeg8-32bit-8.0.2-33.1.x86_64
libjpeg8-8.0.2-33.1.x86_64
libjpeg62-devel-62.1.0-33.1.x86_64
libjpeg62-62.1.0-33.1.x86_64
libjpeg-turbo-1.3.1-33.1.x86_64

libpng16-16-1.6.8-8.1.x86_64
libpng16-devel-1.6.8-8.1.x86_64
libpng12-0-1.2.50-9.1.x86_64
libpng12-0-32bit-1.2.50-9.1.x86_64
libpng16-16-32bit-1.6.8-8.1.x86_64
libpng16-compat-devel-1.6.8-8.1.x86_64
libpng15-15-1.5.22-4.4.x86_64
</pre>

That list is quite likely too long for building headmore.

**Comment by HouzuoGuo** [comment]
oops, Leap 42.1 is now EOL :1234:
